### ISSUE TITLE
reference paper

### ISSUE THREAD

**Issue by Jeff860530** [Tony-Tan/ML#1]
can i get your reference paper?

**Comment by Tony-Tan** [comment]
Do you mean where the algorithms come from?

**Comment by Tony-Tan** [comment]
All the algorithms are described in  "pattern recognition and machine learning" by Bishop.

**Comment by Jeff860530** [comment]
Ok thanks  .
Are you the first author of this code?
And did you test about any other task?
For example multi-class classification

DIPpro <notifications@github.com>於 2020年3月11日 週三，15:32寫道：

**Comment by Tony-Tan** [comment]
Yes, I write this project myself. 
These are all I've tested in the project. 
The multi-class classification has not been studied now.
